[package]
name = "todo_list"
version = "1.0.0"

[addresses]
todo_addr = "0x703a7444c3a7dc43b8dce76feab7b3e74185e8637fe5dca4a0f3650d87f84667"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.19.0"
subdir = "aptos-move/framework/aptos-framework"